sonar.projectKey=UiPath_uipath-integrations-python
sonar.organization=ui
sonar.host.url=https://sonarcloud.io

sonar.sources=packages/uipath-llamaindex/src,packages/uipath-openai-agents/src,packages/uipath-google-adk/src,packages/uipath-pydantic-ai/src,packages/uipath-agent-framework/src,packages/uipath-claude-sdk/src
sonar.tests=packages/uipath-llamaindex/tests,packages/uipath-openai-agents/tests,packages/uipath-google-adk/tests,packages/uipath-pydantic-ai/tests,packages/uipath-agent-framework/tests,packages/uipath-claude-sdk/tests

sonar.python.version=3.11,3.12,3.13
sonar.python.coverage.reportPaths=packages/uipath-llamaindex/coverage.xml,packages/uipath-openai-agents/coverage.xml,packages/uipath-google-adk/coverage.xml,packages/uipath-pydantic-ai/coverage.xml,packages/uipath-agent-framework/coverage.xml,packages/uipath-claude-sdk/coverage.xml

sonar.exclusions=**/samples/**,**/testcases/**,**/template/**

sonar.sourceEncoding=UTF-8
